const QUERY = {
  AUTH: {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    VERIFY_EMAIL_AND_CREATE_PASSWORD: "VERIFY_EMAIL_AND_CREATE_PASSWORD",
  },

  PROJECT: {
    GET_PROJECT: "GET_PROJECT",
  },

  MEMBER: {
    GET_MEMBERS: "GET_MEMBERS",
  },

  TASK: {
    GET_TASKS: "GET_TASKS",
  },
};

export default QUERY;
