const QUERY = {
  AUTH: {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    VERIFY_EMAIL_AND_CREATE_PASSWORD: "VERIFY_EMAIL_AND_CREATE_PASSWORD",
  },

  PROJECT: {
    GET_PROJECT: "GET_PROJECT",
  },
};

export default QUERY;
